In [13]:
#Inserting and Exporting
import numpy as np

In [ ]:
#To Read data from csv file
d = pd.read_csv('Data/Student_Weight_Status_Category_Repor ting_Results__Beginning_2010.csv')

In [ ]:
#To write data to csv file
d= {'C1':pd.Series(['A','B','C']),'C2':pd.Series([1,2,3])}
df= pd.DataFrame(d)
df.to_csv('sampledata.csv')

In [ ]:
#XLS
#xlrd package need to be installed for pandas to read data from excel
d = pd.read_excel('Data/Student_Weight_Status_Category_Repor ting_Results__Beginning_2010.xls')

In [ ]:
#To write an excel xlwt package needs to be installed
df.to_excel('sampledata.xls')

In [ ]:
#JSON
import json
json_data=open('Data/Student_Weight_Status_Category_Reporting_Re sults__Beginning_2010.json') 
data=json.load(json_data)
json_data.close()

In [ ]:
open() function opens a connection to the file.
The json.load() function loads the data into Python.
The json_data.close() function closes the connection to the file.

In [ ]:
The pandas library also provides a function to read the JSON file, which can be accessed using pd.read_json().

In [ ]:
#Database
To read data from a database, the following function can be used:
pd.read_sql_table(table_name,con)

In [ ]:
table_name: This refers to the name of the SQL table in a database
con:This refers to the SQLAlchemy engine

In [ ]:
The following command reads SQL query into a DataFrame:
pd.read_sql_query(sql,con)

In [ ]:
sql:This refers to the SQL query that is to be executed 
con:This refers to the SQLAlchemy engine

In [3]:
#To Read data from csv file
import pandas as pd
d = pd.read_csv('C:\\Users\\Sai\\Downloads\\Udemy_Python\\datacode\\carprice.csv')

In [4]:
d.columns

Index(['car_id', 'price', 'Kilometers', 'hp', 'Brand', 'Sport', 'age', 'Users',
       'gas', 'Metalilic', 'CC', 'Weight', 'QuartTax', 'Automatic', 'red',
       'Owner_gender', 'door'],
      dtype='object')

In [8]:
d['car_id'].isnull()
#d['car_id'].notnull()

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
        ...
5209    False
5210    False
5211    False
5212    False
5213    False
5214    False
5215    False
5216    False
5217    False
5218    False
5219    False
5220    False
5221    False
5222    False
5223    False
5224    False
5225    False
5226    False
5227    False
5228    False
5229    False
5230    False
5231    False
5232    False
5233    False
5234    False
5235    False
5236    False
5237    False
5238    False
Name: car_id, Length: 5239, dtype: bool

In [10]:
d['car_id'].isnull().value_counts()

False    5239
Name: car_id, dtype: int64

In [11]:
d= d['car_id'].drop.na()  #to remove rows
d=d.dropna(how='any') #to remove all rows with an instance of missing values

,car_id,price,Kilometers,hp,Brand,Sport,age,Users,gas,Metalilic,CC,Weight,QuartTax,Automatic,red,Owner_gender,door
0,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5209,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5210,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5211,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
5212,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5213,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5214,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5215,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5216,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5217,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5218,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False
5219,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5220,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5221,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5222,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5223,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5224,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
5225,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5226,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5227,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
5228,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5229,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5230,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5231,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5232,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5233,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5234,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5235,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5236,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5237,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5238,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
#Find Missing values

In [15]:
df=pd.DataFrame(np.random.randn(5,3),index=['a0','a10','a20','a30','a40'],columns=['x','y','z'])
df

            x         y         z
a0  -1.158503  0.554803 -0.342949
a10  1.257937  2.168618  0.076566
a20 -2.276164  0.217134 -1.009162
a30  0.958034 -1.652136  1.606002
a40 -0.431957 -0.332301  1.116338

In [19]:
df2=df.reindex(['a0','a10','a20','a28','a30','a40'])  #adding some extra row indexes, which will create null values in our DataFrame:

df2

            x         y         z
a0  -1.158503  0.554803 -0.342949
a10  1.257937  2.168618  0.076566
a20 -2.276164  0.217134 -1.009162
a28       NaN       NaN       NaN
a30  0.958034 -1.652136  1.606002
a40 -0.431957 -0.332301  1.116338

In [20]:
#If we want to replace null values with zero
df2.fillna(0)

            x         y         z
a0  -1.158503  0.554803 -0.342949
a10  1.257937  2.168618  0.076566
a20 -2.276164  0.217134 -1.009162
a28  0.000000  0.000000  0.000000
a30  0.958034 -1.652136  1.606002
a40 -0.431957 -0.332301  1.116338

In [21]:
#If we want to fill null value with forward propagation, which means value previous to null value in the column will be used to fill null value
df2.fillna(method='pad')

            x         y         z
a0  -1.158503  0.554803 -0.342949
a10  1.257937  2.168618  0.076566
a20 -2.276164  0.217134 -1.009162
a28 -2.276164  0.217134 -1.009162
a30  0.958034 -1.652136  1.606002
a40 -0.431957 -0.332301  1.116338

In [23]:
df2.fillna(df2.mean()) #fill with mean

            x         y         z
a0  -1.158503  0.554803 -0.342949
a10  1.257937  2.168618  0.076566
a20 -2.276164  0.217134 -1.009162
a28 -0.330131  0.191224  0.289359
a30  0.958034 -1.652136  1.606002
a40 -0.431957 -0.332301  1.116338